services:

  app:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app


